# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UeWU65798naRoKcQVuEJbe0O11YFaGyl
"""

import pickle
import pandas as pd
from tensorflow.keras.models import load_model

import pickle
import pandas as pd
from tensorflow.keras.models import load_model

from google.colab import files
files.upload()
# upload churn_model.h5, scaler.pkl, gender_encoder.pkl, geo_encoder.pkl, feature_columns.pkl

model = load_model("churn_model.h5")

with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

with open("gender_encoder.pkl", "rb") as f:
    gender_encoder = pickle.load(f)

with open("geo_encoder.pkl", "rb") as f:
    geo_encoder = pickle.load(f)

with open("feature_columns.pkl", "rb") as f:
    feature_columns = pickle.load(f)

input_data = {
    "CreditScore": 600,
    "Geography": "France",
    "Gender": "Male",
    "Age": 42,
    "Tenure": 3,
    "Balance": 60000,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 1,
    "EstimatedSalary": 50000
}

gender_val = gender_encoder.transform([input_data["Gender"]])[0]

geo_ohe = geo_encoder.transform(
    pd.DataFrame({"Geography": [input_data["Geography"]]})
)

geo_cols = geo_encoder.get_feature_names_out(["Geography"])
geo_df = pd.DataFrame(geo_ohe, columns=geo_cols)

base_df = pd.DataFrame([{
    "CreditScore": input_data["CreditScore"],
    "Gender": gender_val,
    "Age": input_data["Age"],
    "Tenure": input_data["Tenure"],
    "Balance": input_data["Balance"],
    "NumOfProducts": input_data["NumOfProducts"],
    "HasCrCard": input_data["HasCrCard"],
    "IsActiveMember": input_data["IsActiveMember"],
    "EstimatedSalary": input_data["EstimatedSalary"]
}])

final_df = pd.concat([base_df, geo_df], axis=1)
final_df = final_df.reindex(columns=feature_columns, fill_value=0)

x_scaled = scaler.transform(final_df)
probability = model.predict(x_scaled)[0][0]

print("Churn Probability:", probability)

if probability >= 0.5:
    print("Customer is likely to churn")
else:
    print("Customer is not likely to churn")