# -*- coding: utf-8 -*-
"""FinalProjectANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U72kLaqynv2eBoQTTjdXe8MAhOF-rQqf
"""

import pickle
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

from google.colab import files
files.upload()   # upload Churn_Modelling.csv

data = pd.read_csv("Churn_Modelling.csv")
data.head()

data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

gender_encoder = LabelEncoder()
data["Gender"] = gender_encoder.fit_transform(data["Gender"])

geo_encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
geo_ohe = geo_encoder.fit_transform(data[["Geography"]])

geo_cols = geo_encoder.get_feature_names_out(["Geography"])
geo_df = pd.DataFrame(geo_ohe, columns=geo_cols)

data = pd.concat([data.drop(["Geography"], axis=1), geo_df], axis=1)

X = data.drop("Exited", axis=1)
y = data["Exited"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = Sequential([
    Dense(64, activation="relu", input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation="relu"),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True
)

model.fit(
    X_train_scaled, y_train,
    validation_data=(X_test_scaled, y_test),
    epochs=100,
    callbacks=[early_stop],
    verbose=1
)

model.save("churn_model.h5")

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

with open("gender_encoder.pkl", "wb") as f:
    pickle.dump(gender_encoder, f)

with open("geo_encoder.pkl", "wb") as f:
    pickle.dump(geo_encoder, f)

with open("feature_columns.pkl", "wb") as f:
    pickle.dump(list(X.columns), f)

print("All artifacts saved successfully")

files.download("churn_model.h5")
files.download("scaler.pkl")
files.download("gender_encoder.pkl")
files.download("geo_encoder.pkl")
files.download("feature_columns.pkl")

